### ISSUE TITLE
Add package check

### ISSUE THREAD

**Issue by tomuben** [exasol/exasol-python-test-framework#17]
## Background

In some cases, a test expects certain packages to be installed in the script-language-container. If this is not the case, the test might fail. For example the minimal flavors don't have many packages installed, which the standard-flavors have. For those cases, it would be good to offer a check function which verifies if a specific package is installed.
Origin of this issue is https://github.com/exasol/script-languages/pull/231

## Acceptance Criteria

Implement a decorator function which can be used like _Skip_, _SkipIf_, taking the package name and language (R, Python,etc) and skips the test if the rquired package is not installed, so for example:

`
@requiresPackage("R", "RCurl")
def test_xml_processing(self):
....
`

**Comment by tkilias** [comment]
Obsolete, exatest will be replaced
