### ISSUE TITLE
Use asyncio instead of asynchat for UdfDebug logger

### ISSUE THREAD

**Issue by tomuben** [exasol/exasol-python-test-framework#26]
## Background

The UdfDebugLogger (which basically forwards all message coming on a server socket to a multiprocessing queue) is implemented using the asyncchat library.
However, according to the [Python documentation](https://docs.python.org/3/library/asynchat.html), the asyncchat library is deprecated since Python3.6, and recommendation is to use [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio) instead.

## Acceptance Criteria

Re-implement the server implementation of the UdfDebug log with asyncio.

**Comment by tkilias** [comment]
Obsolete, exatest will be replaced in future
